_target_: src.models.label_module.LabelLitModule
_convert_: object

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: 0.001
  weight_decay: 0.0

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.1
  patience: 5

net:
  _target_: src.models.components.activity_net.ActivityNetBinary
  input_dim: ${eval:'2 if ${data.act} else 1'}
  hidden_dim: 64
  num_layers: 2
  dropout: 0.3

# compile model for faster training with pytorch 2.0
compile: false
